language: objective-c

rvm:
  - system
  - 2.0.0

before_install:
    - sudo rake install

script:
    - kitchenplan setup https://github.com/kitchenplan/kitchenplan-config-test.git
    - kitchenplan provision
#    - sudo rake test
