groups:
    - bash
    - developer
    - smartie
recipes:
    global:
        - dotfiles::sshconfig
    mac_os_x:
        - applications::dropbox
        - applications::istatmenus4
        - applications::kaleidoscope
        - applications::omnigraffle
        - applications::things
        - applications::tower
        - applications::viscosity
        - applications::vlc
        - applications::alfred
        - applications::totalfinder
        - applications::cord
        - applications::gcc42
        - applications::hipchat
        - applications::nodejs
        - applications::spotify
        - applications::ssh_config
        - osxdefaults::disable_disk_image_verification
        - osxdefaults::disable_front_row
        - osxdefaults::disable_gatekeeper
        - osxdefaults::do_not_group_windows_by_application_in_mission_control
        - osxdefaults::do_not_show_dashboard_as_a_space
        - osxdefaults::enable_assistive_devices
        - osxdefaults::enable_full_keyboard_access_for_all_controls
        - osxdefaults::increase_window_resize_speed_for_cocoa_applications
        - osxdefaults::make_safari_search_banners_default_to_contains_instead_of_starts_with
        - osxdefaults::prevent_time_machine_from_prompting_to_use_new_hard_drives_as_backup_volume
        - osxdefaults::speed_up_mission_control_animations
        - osxdefaults::set_computer_name
        - osxdefaults::tap_to_click
        - osxdefaults::mail_check_for_new_messages
        - osxdefaults::mail_when_searching_do_not_include_trash
        - osxdefaults::mail_copy_email_addresses_instead_of_names_in_mail
        - osxdefaults::mail_disable_send_and_reply_animations_in_mail
        - osxdefaults::dock_automatically_hide_and_show_the_dock
        - osxdefaults::dock_do_not_animate_opening_applications_from_the_dock
        - osxdefaults::dock_enable_spring_loading_for_all_dock_items
        - osxdefaults::dock_make_dock_icons_of_hidden_applications_translucent
        - osxdefaults::dock_minimize_to_application
        - osxdefaults::dock_set_the_icon_size_of_dock_items_to_36_pixels
        - osxdefaults::dock_show_indicator_lights_for_open_applications_in_the_dock
        - osxdefaults::dock_position_the_dock_on_the_left_side
        - osxdefaults::dock_enable_highlight_hover_effect_for_the_grid_view_of_a_stack
        - osxdefaults::dock_remove_the_animation_when_hiding_showing_the_dock
        - osxdefaults::dock_remove_the_auto-hiding_dock_delay
        - osxdefaults::menu_add_battery_percentage
        - osxdefaults::menu_show_clock_with_date
        - osxdefaults::mail_when_searching_do_not_include_trash
        - osxdefaults::mail_copy_email_addresses_instead_of_names_in_mail
        - osxdefaults::set_computer_name
attributes:
    kdeploydeps:
	php: php54
    git:
        name: Roderik van der Veer
        email: roderik@vanderveer.be
    osxdefaults:
        computername: Sinope
    dotfiles:
        vimusers:
            - root
            - roderik
        kdeploy:
            hostname: dev
        vim:
            bundle:
                - sleuth: git://github.com/tpope/vim-sleuth.git
                - sensible: git://github.com/tpope/vim-sensible.git
                - gitgutter: git://github.com/airblade/vim-gitgutter.git
                - airline: https://github.com/bling/vim-airline
                - syntastic: git://github.com/scrooloose/syntastic.git
                - nerdtree: https://github.com/scrooloose/nerdtree.git
    git:
        name: Roderik van der Veer
        email: roderik.van.der.veer@kunstmaan.be
    osxdefaults:
        computername: Mir
    authorization:
        sudo:
            users:
                - roderik
            passwordless: true
            include_sudoers_d: true
    homebrewalt:
        cask_apps:
            - onepassword
            - dropbox
            - evernote
            - istat-menus
            - kaleidoscope
            - alfred
            - totalfinder
            - spotify
            - bartender
            - vmware-fusion
            - virtualbox
            - vagrant
            - hazel
