groups:
    - bash
    - developer
    - smartie
recipes:
    global:
    mac_os_x:
        - applications::1password
        - applications::dropbox
        - applications::evernote
        - applications::istatmenus4
        - applications::kaleidoscope
        - applications::omnigraffle
        - applications::things
        - applications::tower
        - applications::viscosity
        - applications::vlc
        - applications::superduper
        - applications::alfred
        - applications::totalfinder
        - applications::cord
        - applications::transmit
        - applications::spotify
        - osxdefaults::dock_automatically_hide_and_show_the_dock
        - osxdefaults::dock_do_not_animate_opening_applications_from_the_dock
        - osxdefaults::dock_enable_spring_loading_for_all_dock_items
        - osxdefaults::dock_make_dock_icons_of_hidden_applications_translucent
        - osxdefaults::dock_minimize_to_application
        - osxdefaults::dock_set_the_icon_size_of_dock_items_to_36_pixels
        - osxdefaults::dock_show_indicator_lights_for_open_applications_in_the_dock
        - osxdefaults::dock_position_the_dock_on_the_left_side
        - osxdefaults::dock_enable_highlight_hover_effect_for_the_grid_view_of_a_stack
        - osxdefaults::dock_remove_the_animation_when_hiding_showing_the_dock
        - osxdefaults::dock_remove_the_auto-hiding_dock_delay
        - osxdefaults::menu_add_battery_percentage
        - osxdefaults::menu_show_clock_with_date
attributes:
    git:
        name: Roderik van der Veer
        email: roderik@vanderveer.be
    osxdefaults:
        computername: Sinope
