groups:
    - smarties
recipes:
    - applications::1password
    - applications::bartender
    - applications::dropbox
    - applications::evernote
    - applications::istatmenus4
    - applications::kaleidoscope
    - applications::omnigraffle
    - applications::things
    - applications::tower
    - applications::viscosity
    - applications::vlc
    - applications::superduper
    - applications::alfred
    - applications::totalfinder
    - applications::omniplan
    - osxdefaults::disable_disk_image_verification
    - osxdefaults::disable_front_row
    - osxdefaults::disable_gatekeeper
    - osxdefaults::do_not_group_windows_by_application_in_mission_control
    - osxdefaults::do_not_show_dashboard_as_a_space
    - osxdefaults::enable_assistive_devices
    - osxdefaults::enable_full_keyboard_access_for_all_controls
    - osxdefaults::increase_window_resize_speed_for_cocoa_applications
    - osxdefaults::make_safari_search_banners_default_to_contains_instead_of_starts_with
    - osxdefaults::prevent_time_machine_from_prompting_to_use_new_hard_drives_as_backup_volume
    - osxdefaults::speed_up_mission_control_animations
    - osxdefaults::set_computer_name
    - osxdefaults::tap_to_click
    - osxdefaults::mail_check_for_new_messages
    - osxdefaults::mail_when_searching_do_not_include_trash
    - osxdefaults::mail_copy_email_addresses_instead_of_names_in_mail
    - osxdefaults::mail_disable_send_and_reply_animations_in_mail
    - osxdefaults::dock_automatically_hide_and_show_the_dock
    - osxdefaults::dock_do_not_animate_opening_applications_from_the_dock
    - osxdefaults::dock_enable_spring_loading_for_all_dock_items
    - osxdefaults::dock_make_dock_icons_of_hidden_applications_translucent
    - osxdefaults::dock_minimize_to_application
    - osxdefaults::dock_set_magnification_on
    - osxdefaults::dock_set_the_icon_size_of_dock_items_to_36_pixels
    - osxdefaults::dock_show_indicator_lights_for_open_applications_in_the_dock
    - osxdefaults::dock_position_the_dock_on_the_left_side
    - osxdefaults::dock_enable_highlight_hover_effect_for_the_grid_view_of_a_stack
    - osxdefaults::dock_remove_the_animation_when_hiding_showing_the_dock
    - osxdefaults::dock_remove_the_auto-hiding_dock_delay
    - osxdefaults::finder_allow_text_selection_in_quick_look
    - osxdefaults::finder_display_full_path
    - osxdefaults::finder_use_column_view_in_all_finder_windows_by_default
    - osxdefaults::finder_new_finder_windows_shows_homefolder
    - osxdefaults::finder_automatically_open_a_new_finder_window_when_a_volume_is_mounted
    - osxdefaults::finder_disable_the_warning_before_emptying_the_trash
    - osxdefaults::finder_disable_the_warning_when_changing_a_file_extension
    - osxdefaults::finder_search_the_current_folder_by_default
    - dotfiles::projects
attributes:
    rvm:
        user_installs:
            -
                user: roderik
                upgrade: head
                default_ruby: 1.9.3-p385
    git:
        name: Roderik van der Veer
        email: roderik@vanderveer.be
    osxdefaults:
        computername: Thor
    dotfiles:
        projects:
            kitchenplan:
                - our-kitchenplan: git@github.com:kitchenplan/our-kitchenplan.git
                - kunstmaan-kitchenplan: git@github.com:Kunstmaan/kitchenplan.git
            bundles:
                - KunstmaanSentryBundle: git@github.com:Kunstmaan/KunstmaanSentryBundle.git
            devops:
                - kms: git@github.com:Kunstmaan/kms.git
                - kstrano: git@github.com:Kunstmaan/kStrano.git
        kdeploy:
            hostname: thor.dev
