recipes:
    - homebrew::bash4
    - homebrew::bash-completion
    - homebrew::coreutils
    - homebrew::findutils
    - homebrew::git
    - homebrew::hub
    - homebrew::gnu-tar
    - homebrew::siege
    - homebrew::watch
    - homebrew::wget
    - homebrew::pwgen
    - homebrew::dnsmasq
    - homebrew::xmlstarlet
    - ruby_build
    - rbenv::system
    - applications::google-chrome
    - applications::firefox
    - applications::sequelpro
    - applications::virtualbox
    - applications::xquartz
    - applications::sublime_text
    - applications::vagrant
    - applications::java
    - applications::composer
    - dotfiles::bash_it
    - dotfiles::inputrc
    - dotfiles::gitconfig
    - dotfiles::kms
    - dotfiles::workspace
attributes:
    rbenv:
        upgrade: true
        rubies:
            -
                name: 1.9.3-p385
                environment: { CC: gcc }
        global: 1.9.3-p385
    drivers:
        xerox: 172.18.19.67
    osxdefaults:
        loginmessage: Property of Kunstmaan NV - 016 300 780 - hello@kunstmaan.be
