recipes:
    - applications::create_var_chef_cache
    - homebrew::bash4
    - homebrew::bash-completion
    - homebrew::coreutils
    - homebrew::findutils
    - homebrew::git
    - homebrew::hub
    - homebrew::gnu-tar
    - homebrew::siege
    - homebrew::watch
    - homebrew::wget
    - homebrew::pwgen
    - homebrew::dnsmasq
    - homebrew::xmlstarlet
    - homebrew::gcc42
    - homebrew::rsync
    - homebrew::pv
    - rvm::user
    - applications::google-chrome
    - applications::firefox
    - applications::sequelpro
    - applications::virtualbox
    - applications::xquartz
    - applications::sublime_text
    - applications::vagrant
    - applications::java
    - applications::composer
    - dotfiles::bash_it
    - dotfiles::inputrc
    - dotfiles::gitconfig
    - dotfiles::kms
    - dotfiles::workspace
    - osxdefaults::set_terminal_profile
    ## kDeploy installation
    - dotfiles::kdeploy
    - homebrew::postgresql
    - homebrew::psycopg2
    - homebrew::mysql
    - homebrew::mysql_python
    - homebrew::apache
    - homebrew::php54
    - osxdefaults::finder_unhide_home
    ## end kDeploy installation
attributes:
    drivers:
        xerox: 172.18.19.67
    osxdefaults:
        loginmessage: Property of Kunstmaan NV - 016 300 780 - hello@kunstmaan.be
    mysql_root_password: "password"
