recipes:
    - homebrew::bash4
    - homebrew::bash-completion
    - homebrew::coreutils
    - homebrew::findutils
    - homebrew::git
    - homebrew::hub
    - homebrew::gnu-tar
    - homebrew::siege
    - homebrew::watch
    - homebrew::wget
    - homebrew::pwgen
    - ruby_build
    - rbenv::system
    - applications::google-chrome
    - applications::firefox
    - applications::sequelpro
    - applications::virtualbox
    - applications::xquartz
    - applications::sublime_text
    - applications::vagrant
    - dotfiles::bash_it
    - dotfiles::inputrc
    - dotfiles::gitconfig
    - dotfiles::kms
attributes:
    rbenv:
        upgrade: true
        rubies:
            - 1.9.3-p385
        global: 1.9.3-p385

