recipes:
    global:
        - applications::git
        - applications::wget
        - applications::pwgen
        - applications::xmlstarlet
        - applications::pv
        - applications::htop
        - dotfiles::gitconfig
        - applications::grunt-cli
        - applications::bower
        - applications::watch
        - applications::gnu-tar
        - applications::sequelpro
        - applications::sourcetree
        - applications::git-flow
        - applications::sass
        - applications::siege
        - applications::nodejs
        - applications::ssh_config
        - dotfiles::vim
        - applications::codekit
        - applications::espresso
        - applications::imageoptim
        - applications::imagealpha
        - applications::svgo
        - applications::sublime_text_3
        - applications::phpstorm
        - applications::composer
    mac_os_x:
        - osxdefaults::set_terminal_profile
        - osxdefaults::add_a_context_menu_item_for_showing_the_web_inspector_in_web_views
        - osxdefaults::disable_press-and-hold_for_keys_in_favor_of_key_repeat
        - osxdefaults::enable_safari_debug_menu
        - osxdefaults::set_a_blazingly_fast_keyboard_repeat_rate
    debian:
        - applications::performance_scheduler
        - applications::nscd
        - applications::locales
        - applications::pureftpd
        - applications::xvfb
        - applications::pidgin
        - applications::ubuntu-desktop
