recipes:
    global:
        - dotfiles::kms
        - dotfiles::workspace
        - applications::postgresql
        - applications::psycopg2
        - applications::mysql
        - applications::mysql_python
        - applications::apache
        - applications::php54
        - dotfiles::kdeploy
    mac_os_x:
        - applications::hipchat
        - osxdefaults::disable_disk_image_verification
        - osxdefaults::disable_gatekeeper
        - osxdefaults::disable_front_row
        - osxdefaults::enable_assistive_devices
        - osxdefaults::enable_full_keyboard_access_for_all_controls
        - osxdefaults::increase_window_resize_speed_for_cocoa_applications
        - osxdefaults::speed_up_mission_control_animations
        - osxdefaults::set_computer_name
        - osxdefaults::tap_to_click
        - osxdefaults::mail_check_for_new_messages
        - osxdefaults::mail_when_searching_do_not_include_trash
        - osxdefaults::mail_copy_email_addresses_instead_of_names_in_mail
        - osxdefaults::mail_disable_send_and_reply_animations_in_mail
        - osxdefaults::do_not_show_dashboard_as_a_space
        - osxdefaults::prevent_time_machine_from_prompting_to_use_new_hard_drives_as_backup_volume
        - osxdefaults::finder_allow_text_selection_in_quick_look
        - osxdefaults::finder_display_full_path
        - osxdefaults::finder_use_column_view_in_all_finder_windows_by_default
        - osxdefaults::finder_new_finder_windows_shows_homefolder
        - osxdefaults::finder_automatically_open_a_new_finder_window_when_a_volume_is_mounted
        - osxdefaults::finder_disable_the_warning_before_emptying_the_trash
        - osxdefaults::finder_disable_the_warning_when_changing_a_file_extension
        - osxdefaults::finder_search_the_current_folder_by_default
        - osxdefaults::finder_unhide_home
    debian:
        - root_ssh_agent::env_keep
        - root_ssh_agent::ppid
        - applications::essentials
        - applications::mysql_workbench
        - applications::server_tuning
        - applications::postfix
        - applications::java
attributes:
    mysql_root_password: "password"
    postfix:
        domain: "kunstmaan.be"
