recipes:
    global:
        - dotfiles::kms
        - dotfiles::kdeploy
    mac_os_x:
        - applications::hipchat
    debian:
        - root_ssh_agent::env_keep
        - root_ssh_agent::ppid
        - applications::essentials
        - applications::mysql_workbench
        - applications::server_tuning
        - applications::postfix
        - applications::java
attributes:
    postfix:
        domain: "kunstmaan.be"
